#!/bin/bash
# resolve-executor.sh - Auto-detect project stack and resolve executor
# Called by Claude Code hooks (PreToolUse, SessionStart)
#
# This script:
# 1. Checks for explicit executor config in .agent-forge/config.yaml
# 2. Auto-detects project stack from files
# 3. Writes executor context for use by commands/agents

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(dirname "$SCRIPT_DIR")"
EXECUTORS_DIR="${PLUGIN_DIR}/executors"
CONTEXT_DIR=".agent-forge"
CONTEXT_FILE="${CONTEXT_DIR}/executor.context"

# Ensure context directory exists
mkdir -p "$CONTEXT_DIR"

# Function to write executor context
write_executor_context() {
    local executor="$1"
    local source="$2"  # "config" or "detected"

    # Get executor metadata if available
    local executor_json="${EXECUTORS_DIR}/${executor}/executor.json"
    local display_name="$executor"
    local description=""

    if [ -f "$executor_json" ]; then
        display_name=$(jq -r '.displayName // .name // empty' "$executor_json" 2>/dev/null || echo "$executor")
        description=$(jq -r '.description // empty' "$executor_json" 2>/dev/null || echo "")
    fi

    # Write context file
    cat > "$CONTEXT_FILE" <<EOF
# Executor Context
# Generated by resolve-executor.sh
# DO NOT EDIT MANUALLY - this file is auto-generated

executor: ${executor}
executor_source: ${source}
executor_display: ${display_name}
$(if [ -n "$description" ]; then echo "executor_description: ${description}"; fi)
detected_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

    echo "[executor-resolver] Detected: ${executor} (source: ${source})" >&2
}

# 1. Check for explicit config in .agent-forge/config.yaml
CONFIG_FILE="${CONTEXT_DIR}/config.yaml"
if [ -f "$CONFIG_FILE" ]; then
    EXECUTOR=$(grep -E "^executor:" "$CONFIG_FILE" | head -1 | sed 's/^executor:[[:space:]]*//' | tr -d '[:space:]')
    if [ -n "$EXECUTOR" ]; then
        write_executor_context "$EXECUTOR" "config"
        exit 0
    fi
fi

# 2. Auto-detect from project files
# Priority order based on specificity

# Kotlin/JVM projects (Gradle)
if [ -f "build.gradle.kts" ] || [ -f "settings.gradle.kts" ]; then
    write_executor_context "kotlin" "detected"
    exit 0
fi

if [ -f "build.gradle" ] || [ -f "settings.gradle" ]; then
    # Could be Groovy Gradle with Kotlin or Java
    # Check for Kotlin sources
    if [ -d "src/main/kotlin" ] || find . -name "*.kt" -type f 2>/dev/null | head -1 | grep -q .; then
        write_executor_context "kotlin" "detected"
        exit 0
    fi
fi

# Rust projects
if [ -f "Cargo.toml" ]; then
    write_executor_context "rust" "detected"
    exit 0
fi

# Python projects
if [ -f "pyproject.toml" ] || [ -f "setup.py" ] || [ -f "setup.cfg" ]; then
    write_executor_context "python" "detected"
    exit 0
fi

# TypeScript/JavaScript projects
if [ -f "package.json" ]; then
    # Check for TypeScript
    if [ -f "tsconfig.json" ] || find . -name "*.ts" -type f 2>/dev/null | head -1 | grep -q .; then
        write_executor_context "typescript" "detected"
        exit 0
    fi
    # Default to typescript for npm/node projects
    write_executor_context "typescript" "detected"
    exit 0
fi

# Go projects
if [ -f "go.mod" ]; then
    write_executor_context "go" "detected"
    exit 0
fi

# 3. Fallback to default executor
write_executor_context "default" "fallback"
exit 0
